/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jm_study_jnidemo_JniMethod */

#ifndef _Included_jm_study_jnidemo_JniMethod
#define _Included_jm_study_jnidemo_JniMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jm_study_jnidemo_JniMethod
 * Method:    getABI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jm_study_jnidemo_JniMethod_getABI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
